default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  user: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  password:

development:
  <<: *default
  database: feelingdb_dev

test:
  <<: *default
  database: feelingdb_test

production:
  <<: *default
  database: feelingdb_prod
